/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { EnergyConsumptionUpdateManyWithoutBuildingsInput } from "./EnergyConsumptionUpdateManyWithoutBuildingsInput";
import { Type } from "class-transformer";
import { HvacSystemUpdateManyWithoutBuildingsInput } from "./HvacSystemUpdateManyWithoutBuildingsInput";
import { RecommendationUpdateManyWithoutBuildingsInput } from "./RecommendationUpdateManyWithoutBuildingsInput";

@InputType()
class BuildingUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  builtYear?: number | null;

  @ApiProperty({
    required: false,
    type: () => EnergyConsumptionUpdateManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => EnergyConsumptionUpdateManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => EnergyConsumptionUpdateManyWithoutBuildingsInput, {
    nullable: true,
  })
  energyConsumptions?: EnergyConsumptionUpdateManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: () => HvacSystemUpdateManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => HvacSystemUpdateManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => HvacSystemUpdateManyWithoutBuildingsInput, {
    nullable: true,
  })
  hvacSystems?: HvacSystemUpdateManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecommendationUpdateManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => RecommendationUpdateManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => RecommendationUpdateManyWithoutBuildingsInput, {
    nullable: true,
  })
  recommendations?: RecommendationUpdateManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalFloors?: number | null;
}

export { BuildingUpdateInput as BuildingUpdateInput };
