/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { EnergyConsumptionCreateNestedManyWithoutBuildingsInput } from "./EnergyConsumptionCreateNestedManyWithoutBuildingsInput";
import { Type } from "class-transformer";
import { HvacSystemCreateNestedManyWithoutBuildingsInput } from "./HvacSystemCreateNestedManyWithoutBuildingsInput";
import { RecommendationCreateNestedManyWithoutBuildingsInput } from "./RecommendationCreateNestedManyWithoutBuildingsInput";

@InputType()
class BuildingCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  builtYear?: number | null;

  @ApiProperty({
    required: false,
    type: () => EnergyConsumptionCreateNestedManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => EnergyConsumptionCreateNestedManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => EnergyConsumptionCreateNestedManyWithoutBuildingsInput, {
    nullable: true,
  })
  energyConsumptions?: EnergyConsumptionCreateNestedManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: () => HvacSystemCreateNestedManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => HvacSystemCreateNestedManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => HvacSystemCreateNestedManyWithoutBuildingsInput, {
    nullable: true,
  })
  hvacSystems?: HvacSystemCreateNestedManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecommendationCreateNestedManyWithoutBuildingsInput,
  })
  @ValidateNested()
  @Type(() => RecommendationCreateNestedManyWithoutBuildingsInput)
  @IsOptional()
  @Field(() => RecommendationCreateNestedManyWithoutBuildingsInput, {
    nullable: true,
  })
  recommendations?: RecommendationCreateNestedManyWithoutBuildingsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalFloors?: number | null;
}

export { BuildingCreateInput as BuildingCreateInput };
