/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HvacSystemService } from "../hvacSystem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HvacSystemCreateInput } from "./HvacSystemCreateInput";
import { HvacSystem } from "./HvacSystem";
import { HvacSystemFindManyArgs } from "./HvacSystemFindManyArgs";
import { HvacSystemWhereUniqueInput } from "./HvacSystemWhereUniqueInput";
import { HvacSystemUpdateInput } from "./HvacSystemUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HvacSystemControllerBase {
  constructor(
    protected readonly service: HvacSystemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HvacSystem })
  @nestAccessControl.UseRoles({
    resource: "HvacSystem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHvacSystem(
    @common.Body() data: HvacSystemCreateInput
  ): Promise<HvacSystem> {
    return await this.service.createHvacSystem({
      data: {
        ...data,

        building: data.building
          ? {
              connect: data.building,
            }
          : undefined,
      },
      select: {
        building: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        maintenanceDate: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HvacSystem] })
  @ApiNestedQuery(HvacSystemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HvacSystem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hvacSystems(@common.Req() request: Request): Promise<HvacSystem[]> {
    const args = plainToClass(HvacSystemFindManyArgs, request.query);
    return this.service.hvacSystems({
      ...args,
      select: {
        building: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        maintenanceDate: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HvacSystem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HvacSystem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hvacSystem(
    @common.Param() params: HvacSystemWhereUniqueInput
  ): Promise<HvacSystem | null> {
    const result = await this.service.hvacSystem({
      where: params,
      select: {
        building: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        maintenanceDate: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HvacSystem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HvacSystem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHvacSystem(
    @common.Param() params: HvacSystemWhereUniqueInput,
    @common.Body() data: HvacSystemUpdateInput
  ): Promise<HvacSystem | null> {
    try {
      return await this.service.updateHvacSystem({
        where: params,
        data: {
          ...data,

          building: data.building
            ? {
                connect: data.building,
              }
            : undefined,
        },
        select: {
          building: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          maintenanceDate: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HvacSystem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HvacSystem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHvacSystem(
    @common.Param() params: HvacSystemWhereUniqueInput
  ): Promise<HvacSystem | null> {
    try {
      return await this.service.deleteHvacSystem({
        where: params,
        select: {
          building: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          maintenanceDate: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
